// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkEmailExist = `-- name: CheckEmailExist :one
SELECT EXISTS(
    SELECT id, created_at, updated_at, deleted_at, email, password, firstname, lastname, role FROM users
    WHERE email = $1
    AND deleted_at IS NULL
)
`

func (q *Queries) CheckEmailExist(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExist, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loginUser = `-- name: LoginUser :one
SELECT id, firstname lastname, email, role FROM users
WHERE email = $1
AND password = crypt($2, password)
AND deleted_at IS NULL
`

type LoginUserParams struct {
	Email string `json:"email"`
	Crypt string `json:"crypt"`
}

type LoginUserRow struct {
	ID       uuid.UUID      `json:"id"`
	Lastname sql.NullString `json:"lastname"`
	Email    string         `json:"email"`
	Role     Role           `json:"role"`
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (LoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Email, arg.Crypt)
	var i LoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Lastname,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const signup = `-- name: Signup :one
INSERT INTO users (email, password, firstname, lastname) 
VALUES ($1, crypt($2, gen_salt('bf')), $3, $4)
RETURNING id, created_at, updated_at, deleted_at, email, password, firstname, lastname, role
`

type SignupParams struct {
	Email     string         `json:"email"`
	Crypt     string         `json:"crypt"`
	Firstname sql.NullString `json:"firstname"`
	Lastname  sql.NullString `json:"lastname"`
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) (User, error) {
	row := q.db.QueryRowContext(ctx, signup,
		arg.Email,
		arg.Crypt,
		arg.Firstname,
		arg.Lastname,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
	)
	return i, err
}
